package com.example.jpa.db;
// Generated 9/10/2017 03:30:25 PM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ListaObjetivos generated by hbm2java
 */
@Entity
@Table(name = "lista_objetivos",
         catalog = "clinical"
)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})

public class ListaObjetivos implements java.io.Serializable {

    private Long objetivoId;
    private Subareas subareas;
    private String nombre;

    public ListaObjetivos() {
    }

    public ListaObjetivos(Subareas subareas, String nombre) {
        this.subareas = subareas;
        this.nombre = nombre;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "objetivo_id", unique = true, nullable = false)
    public Long getObjetivoId() {
        return this.objetivoId;
    }

    public void setObjetivoId(Long objetivoId) {
        this.objetivoId = objetivoId;
    }

    @JsonIgnore
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "subarea", nullable = false)
    public Subareas getSubareas() {
        return this.subareas;
    }

    public void setSubareas(Subareas subareas) {
        this.subareas = subareas;
    }

    @Column(name = "nombre", nullable = false, length = 250)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}
