package com.example.jpa.db;
// Generated Sep 15, 2017 11:44:15 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ObjetivoCurriculum generated by hbm2java
 */
@Entity
@Table(name="objetivoscurriculum"
    ,catalog="clinical"
)
public class ObjetivoCurriculum  implements java.io.Serializable {


     private Long objetivoId;
     private Person persons;
     private String area;
     private String estado;
     private String subarea;
     private String nombreObjetivo;
     private Set<PuntuacionCuatrimestral> puntuacionescuatrimestrals = new HashSet<PuntuacionCuatrimestral>(0);

    public ObjetivoCurriculum() {
    }

	
    public ObjetivoCurriculum(Person persons, String area, String estado, String subarea, String nombreObjetivo) {
        this.persons = persons;
        this.area = area;
        this.estado = estado;
        this.subarea = subarea;
        this.nombreObjetivo = nombreObjetivo;
    }
    public ObjetivoCurriculum(Person persons, String area, String estado, String subarea, String nombreObjetivo, Set<PuntuacionCuatrimestral> puntuacionescuatrimestrals) {
       this.persons = persons;
       this.area = area;
       this.estado = estado;
       this.subarea = subarea;
       this.nombreObjetivo = nombreObjetivo;
       this.puntuacionescuatrimestrals = puntuacionescuatrimestrals;
    }
   
     @Id
     @GeneratedValue(strategy=GenerationType.AUTO)    
    @Column(name="objetivo_id", unique=true, nullable=false)
    public Long getObjetivoId() {
        return this.objetivoId;
    }
    
    public void setObjetivoId(Long objetivoId) {
        this.objetivoId = objetivoId;
    }
@JsonIgnore
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="persons_id", nullable=false)
    public Person getPersons() {
        return this.persons;
    }
    
    public void setPersons(Person persons) {
        this.persons = persons;
    }

    
    @Column(name="area", nullable=false, length=65535)
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }

    
    @Column(name="estado", nullable=false, length=65535)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="subarea", nullable=false, length=65535)
    public String getSubarea() {
        return this.subarea;
    }
    
    public void setSubarea(String subarea) {
        this.subarea = subarea;
    }

    
    @Column(name="nombre_objetivo", nullable=false, length=65535)
    public String getNombreObjetivo() {
        return this.nombreObjetivo;
    }
    
    public void setNombreObjetivo(String nombreObjetivo) {
        this.nombreObjetivo = nombreObjetivo;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="objetivoscurriculum",cascade = CascadeType.ALL)
    public Set<PuntuacionCuatrimestral> getPuntuacionescuatrimestrals() {
        return this.puntuacionescuatrimestrals;
    }
    
    public void setPuntuacionescuatrimestrals(Set<PuntuacionCuatrimestral> puntuacionescuatrimestrals) {
        this.puntuacionescuatrimestrals = puntuacionescuatrimestrals;
    }




}


