package com.example.jpa.db;
// Generated Sep 15, 2017 11:44:15 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cascade;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "persons",
         catalog = "clinical"
)
public class Person implements java.io.Serializable {

    private long id;
    private String name;
    private String sexo;
    private String lugarDeNacimiento;
    private Date fechaDeNacimiento;
    private Integer numeroDocumento;
    private String ciudad;
    private String localidad;
    private String barrio;
    private String nombrePadre;
    private Date fechaNacimientoPadre;
    private String ocupacionPadre;
    private Long telefonoPadre;
    private String nombrMadre;
    private Date fechaNacimientoMadre;
    private String ocupacionMadre;
    private Long telefonoMadre;
    private String aseguradora;
    private String vinculacion;
    private String password;
    private String role;
    private String historiaDelProblema;
    private String metodoDeEvaluacion;
    private String informacionGeneral;
    private String actividadesBasicasGenerales;
    private String habilidadesEspeciales;
    private String areasDeEvaluacion;
    private String problemasComportamentales;
    private String psicologia;
    private String resultados;
    private String analisisDeCriteriosDiagnostico;
    private String compromiso;
    private Set<Objetivo> programaIndividual = new HashSet<Objetivo>(0);
    private Set<ObjetivoCurriculum> objetivoscurriculums = new HashSet<ObjetivoCurriculum>(0);

    public Person() {
    }

    public Person(long id) {
        this.id = id;
    }

    public Person(long id, String name, String sexo, String lugarDeNacimiento, Date fechaDeNacimiento, Integer numeroDocumento, String ciudad, String localidad, String barrio, String nombrePadre, Date edadPadre, String ocupacionPadre, Long telefonoPadre, String nombrMadre, Date edadMadre, String ocupacionMadre, Long telefonoMadre, String aseguradora, String vinculacion, String password, String role, String historiaDelProblema, String metodoDeEvaluacion, String informacionGeneral, String actividadesBasicasGenerales, String habilidadesEspeciales, String areasDeEvaluacion, String problemasComportamentales, String psicologia, String resultados, String analisisDeCriteriosDiagnostico, String compromiso, Set<Objetivo> objetivoses, Set<ObjetivoCurriculum> objetivoscurriculums) {
        this.id = id;
        this.name = name;
        this.sexo = sexo;
        this.lugarDeNacimiento = lugarDeNacimiento;
        this.fechaDeNacimiento = fechaDeNacimiento;
        this.numeroDocumento = numeroDocumento;
        this.ciudad = ciudad;
        this.localidad = localidad;
        this.barrio = barrio;
        this.nombrePadre = nombrePadre;
        this.fechaNacimientoPadre = edadPadre;
        this.ocupacionPadre = ocupacionPadre;
        this.telefonoPadre = telefonoPadre;
        this.nombrMadre = nombrMadre;
        this.fechaNacimientoMadre = edadMadre;
        this.ocupacionMadre = ocupacionMadre;
        this.telefonoMadre = telefonoMadre;
        this.aseguradora = aseguradora;
        this.vinculacion = vinculacion;
        this.password = password;
        this.role = role;
        this.historiaDelProblema = historiaDelProblema;
        this.metodoDeEvaluacion = metodoDeEvaluacion;
        this.informacionGeneral = informacionGeneral;
        this.actividadesBasicasGenerales = actividadesBasicasGenerales;
        this.habilidadesEspeciales = habilidadesEspeciales;
        this.areasDeEvaluacion = areasDeEvaluacion;
        this.problemasComportamentales = problemasComportamentales;
        this.psicologia = psicologia;
        this.resultados = resultados;
        this.analisisDeCriteriosDiagnostico = analisisDeCriteriosDiagnostico;
        this.compromiso = compromiso;
        this.programaIndividual = objetivoses;
        this.objetivoscurriculums = objetivoscurriculums;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "name", length = 65535)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "sexo", length = 65535)
    public String getSexo() {
        return this.sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Column(name = "lugar_de_nacimiento", length = 65535)
    public String getLugarDeNacimiento() {
        return this.lugarDeNacimiento;
    }

    public void setLugarDeNacimiento(String lugarDeNacimiento) {
        this.lugarDeNacimiento = lugarDeNacimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_de_nacimiento", length = 10)
    public Date getFechaDeNacimiento() {
        return this.fechaDeNacimiento;
    }

    public void setFechaDeNacimiento(Date fechaDeNacimiento) {
        this.fechaDeNacimiento = fechaDeNacimiento;
    }

    @Column(name = "numero_documento")
    public Integer getNumeroDocumento() {
        return this.numeroDocumento;
    }

    public void setNumeroDocumento(Integer numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

    @Column(name = "ciudad", length = 65535)
    public String getCiudad() {
        return this.ciudad;
    }

    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    @Column(name = "localidad", length = 65535)
    public String getLocalidad() {
        return this.localidad;
    }

    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }

    @Column(name = "barrio", length = 65535)
    public String getBarrio() {
        return this.barrio;
    }

    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }

    @Column(name = "nombre_padre", length = 65535)
    public String getNombrePadre() {
        return this.nombrePadre;
    }

    public void setNombrePadre(String nombrePadre) {
        this.nombrePadre = nombrePadre;
    }

    @Column(name = "edad_padre")
    public Date getFechaNacimientoPadre() {
        return this.fechaNacimientoPadre;
    }

    public void setFechaNacimientoPadre(Date fechaNacimientoPadre) {
        this.fechaNacimientoPadre = fechaNacimientoPadre;
    }

    @Column(name = "ocupacion_padre", length = 65535)
    public String getOcupacionPadre() {
        return this.ocupacionPadre;
    }

    public void setOcupacionPadre(String ocupacionPadre) {
        this.ocupacionPadre = ocupacionPadre;
    }

    @Column(name = "telefono_padre")
    public Long getTelefonoPadre() {
        return this.telefonoPadre;
    }

    public void setTelefonoPadre(Long telefonoPadre) {
        this.telefonoPadre = telefonoPadre;
    }

    @Column(name = "nombr_madre", length = 65535)
    public String getNombrMadre() {
        return this.nombrMadre;
    }

    public void setNombrMadre(String nombrMadre) {
        this.nombrMadre = nombrMadre;
    }

    @Column(name = "edad_madre")
    public Date getFechaNacimientoMadre() {
        return this.fechaNacimientoMadre;
    }

    public void setFechaNacimientoMadre(Date fechaNacimientoMadre) {
        this.fechaNacimientoMadre = fechaNacimientoMadre;
    }

    @Column(name = "ocupacion_madre", length = 65535)
    public String getOcupacionMadre() {
        return this.ocupacionMadre;
    }

    public void setOcupacionMadre(String ocupacionMadre) {
        this.ocupacionMadre = ocupacionMadre;
    }

    @Column(name = "telefono_madre")
    public Long getTelefonoMadre() {
        return this.telefonoMadre;
    }

    public void setTelefonoMadre(Long telefonoMadre) {
        this.telefonoMadre = telefonoMadre;
    }

    @Column(name = "aseguradora", length = 65535)
    public String getAseguradora() {
        return this.aseguradora;
    }

    public void setAseguradora(String aseguradora) {
        this.aseguradora = aseguradora;
    }

    @Column(name = "vinculacion", length = 65535)
    public String getVinculacion() {
        return this.vinculacion;
    }

    public void setVinculacion(String vinculacion) {
        this.vinculacion = vinculacion;
    }

    @Column(name = "password", length = 65535)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "role", length = 65535)
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @Column(name = "historia_del_problema", length = 65535)
    public String getHistoriaDelProblema() {
        return this.historiaDelProblema;
    }

    public void setHistoriaDelProblema(String historiaDelProblema) {
        this.historiaDelProblema = historiaDelProblema;
    }

    @Column(name = "metodo_de_evaluacion", length = 65535)
    public String getMetodoDeEvaluacion() {
        return this.metodoDeEvaluacion;
    }

    public void setMetodoDeEvaluacion(String metodoDeEvaluacion) {
        this.metodoDeEvaluacion = metodoDeEvaluacion;
    }

    @Column(name = "informacion_general", length = 65535)
    public String getInformacionGeneral() {
        return this.informacionGeneral;
    }

    public void setInformacionGeneral(String informacionGeneral) {
        this.informacionGeneral = informacionGeneral;
    }

    @Column(name = "actividades_basicas_generales", length = 65535)
    public String getActividadesBasicasGenerales() {
        return this.actividadesBasicasGenerales;
    }

    public void setActividadesBasicasGenerales(String actividadesBasicasGenerales) {
        this.actividadesBasicasGenerales = actividadesBasicasGenerales;
    }

    @Column(name = "habilidades_especiales", length = 65535)
    public String getHabilidadesEspeciales() {
        return this.habilidadesEspeciales;
    }

    public void setHabilidadesEspeciales(String habilidadesEspeciales) {
        this.habilidadesEspeciales = habilidadesEspeciales;
    }

    @Column(name = "areas_de_evaluacion", length = 65535)
    public String getAreasDeEvaluacion() {
        return this.areasDeEvaluacion;
    }

    public void setAreasDeEvaluacion(String areasDeEvaluacion) {
        this.areasDeEvaluacion = areasDeEvaluacion;
    }

    @Column(name = "problemas_comportamentales", length = 65535)
    public String getProblemasComportamentales() {
        return this.problemasComportamentales;
    }

    public void setProblemasComportamentales(String problemasComportamentales) {
        this.problemasComportamentales = problemasComportamentales;
    }

    @Column(name = "psicologia", length = 65535)
    public String getPsicologia() {
        return this.psicologia;
    }

    public void setPsicologia(String psicologia) {
        this.psicologia = psicologia;
    }

    @Column(name = "resultados", length = 65535)
    public String getResultados() {
        return this.resultados;
    }

    public void setResultados(String resultados) {
        this.resultados = resultados;
    }

    @Column(name = "analisis_de_criterios_diagnostico", length = 65535)
    public String getAnalisisDeCriteriosDiagnostico() {
        return this.analisisDeCriteriosDiagnostico;
    }

    public void setAnalisisDeCriteriosDiagnostico(String analisisDeCriteriosDiagnostico) {
        this.analisisDeCriteriosDiagnostico = analisisDeCriteriosDiagnostico;
    }

    @Column(name = "compromiso", length = 65535)
    public String getCompromiso() {
        return this.compromiso;
    }

    public void setCompromiso(String compromiso) {
        this.compromiso = compromiso;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "persons", cascade = CascadeType.ALL)
    public Set<Objetivo> getProgramaIndividual() {
        return this.programaIndividual;
    }

    public void setProgramaIndividual(Set<Objetivo> programaIndividual) {
        this.programaIndividual = programaIndividual;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "persons", cascade = CascadeType.ALL)
    public Set<ObjetivoCurriculum> getObjetivoscurriculums() {
        return this.objetivoscurriculums;
    }

    public void setObjetivoscurriculums(Set<ObjetivoCurriculum> objetivoscurriculums) {
        this.objetivoscurriculums = objetivoscurriculums;
    }

}
