package com.example.jpa.db;
// Generated Sep 15, 2017 11:44:15 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PuntuacionCuatrimestral generated by hbm2java
 */
@Entity
@Table(name="puntuacionescuatrimestral"
    ,catalog="clinical"
)
public class PuntuacionCuatrimestral  implements java.io.Serializable {


     private Long puntuacioncuatrimestralId;
     private ObjetivoCurriculum objetivoscurriculum;
     private String puntuacion;
     private Date fecha;
     private int tipo;

    public PuntuacionCuatrimestral() {
    }

    public PuntuacionCuatrimestral(ObjetivoCurriculum objetivoscurriculum, String puntuacion, Date fecha, int tipo) {
       this.objetivoscurriculum = objetivoscurriculum;
       this.puntuacion = puntuacion;
       this.fecha = fecha;
       this.tipo = tipo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="puntuacioncuatrimestral_id", unique=true, nullable=false)
    public Long getPuntuacioncuatrimestralId() {
        return this.puntuacioncuatrimestralId;
    }
    
    public void setPuntuacioncuatrimestralId(Long puntuacioncuatrimestralId) {
        this.puntuacioncuatrimestralId = puntuacioncuatrimestralId;
    }
@JsonIgnore
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="objetivoscurriculum_objetivo_id", nullable=false)
    public ObjetivoCurriculum getObjetivoscurriculum() {
        return this.objetivoscurriculum;
    }
    
    public void setObjetivoscurriculum(ObjetivoCurriculum objetivoscurriculum) {
        this.objetivoscurriculum = objetivoscurriculum;
    }

    
    @Column(name="puntuacion", nullable=false, length=65535)
    public String getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(String puntuacion) {
        this.puntuacion = puntuacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="tipo", nullable=false)
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }




}


