package com.example.jpa.db;
// Generated 9/10/2017 03:30:25 PM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subareas generated by hbm2java
 */
@Entity
@Table(name="subareas"
    ,catalog="clinical"
)
public class Subareas  implements java.io.Serializable {


     private Long subareaId;
     private Areas areas;
     private String nombre;
     private Set<ListaObjetivos> listaObjetivoses = new HashSet<ListaObjetivos>(0);

    public Subareas() {
    }

	
    public Subareas(Areas areas, String nombre) {
        this.areas = areas;
        this.nombre = nombre;
    }
    public Subareas(Areas areas, String nombre, Set<ListaObjetivos> listaObjetivoses) {
       this.areas = areas;
       this.nombre = nombre;
       this.listaObjetivoses = listaObjetivoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="subarea_id", unique=true, nullable=false)
    public Long getSubareaId() {
        return this.subareaId;
    }
    
    public void setSubareaId(Long subareaId) {
        this.subareaId = subareaId;
    }
@JsonIgnore
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="area", nullable=false)
    public Areas getAreas() {
        return this.areas;
    }
    
    public void setAreas(Areas areas) {
        this.areas = areas;
    }

    
    @Column(name="nombre", nullable=false, length=250)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subareas")
    public Set<ListaObjetivos> getListaObjetivoses() {
        return this.listaObjetivoses;
    }
    
    public void setListaObjetivoses(Set<ListaObjetivos> listaObjetivoses) {
        this.listaObjetivoses = listaObjetivoses;
    }




}


